on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Build Commands
        run: |
          echo "--- Runner Hostname ---"
          hostname
          
          echo "--- Python Version Check ---"
          python3 --version
          
          echo "--- Build Status ---"
          echo "Compile complete."

      - name: Verify File Existence
        run: |
          echo "Current working directory is: $(pwd)"
          echo "Checking if file exists in: $GITHUB_WORKSPACE/${{ env.PYTHON_SCRIPT_PATH }}"
          ls -l $GITHUB_WORKSPACE/${{ env.PYTHON_SCRIPT_PATH }}
          if [ ! -f $GITHUB_WORKSPACE/${{ env.PYTHON_SCRIPT_PATH }} ]; then
            echo "--- ERROR: File was not found after checkout. Please check the commit history. ---"
            exit 1
          fi

      - name: Deploy Virtual Environment and Run Script
        run: |
          python -m venv venvRG
          
          source venvRG/bin/activate 
          
          ./venvRG/bin/python "$GITHUB_WORKSPACE/${{ env.PYTHON_SCRIPT_PATH }}"

          deactivate

          echo "--- Cleaning up venvRG folder ---"
          rm -rf venvRG
          
          echo "Virtual environment cleanup complete."
