name: File Existence Check Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code (Deep Clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Script in Workspace (CRITICAL TEST)
        id: find_file
        run: |
          WORKSPACE_ROOT=$(pwd)
          
          echo "--- Starting Search for randomgrid.py in: $GITHUB_WORKSPACE ---"
          
          # Use 'find' to locate the file anywhere under the workspace root
          FOUND_PATH=$(find "$GITHUB_WORKSPACE" -name "randomgrid.py" 2>/dev/null)
          
          if [ -z "$FOUND_PATH" ]; then
            echo "::error::File 'randomgrid.py' NOT FOUND anywhere in the checked-out repository."
            echo "Current PWD: $WORKSPACE_ROOT"
            echo "Contents of app/ directory:"
            ls -al app/
            echo "Contents of Repository Root:"
            ls -al $GITHUB_WORKSPACE
            exit 1
          else
            echo "::notice::SUCCESS! File found at: $FOUND_PATH"
            echo "FOUND_PATH=$FOUND_PATH" >> $GITHUB_OUTPUT
          fi
          
      - name: SUCCESS - File Found
        if: success() && steps.find_file.outputs.FOUND_PATH != ''
        run: echo "The file was successfully located. The path error is fixed."
        
      # You can add the real Python execution steps back here once this test passes.
