on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Build Commands
        run: |
          echo "--- Runner Hostname ---"
          hostname
          
          echo "--- Python Version Check ---"
          python3 --version
          
          echo "--- Build Status ---"
          echo "Compile complete."
