on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Build Commands
        run: |
          echo "--- Runner Hostname ---"
          hostname
          
          echo "--- Python Version Check ---"
          python3 --version
          
          echo "--- Build Status ---"
          echo "Compile complete."


      - name: Deploy Virtual Environment and Run Script
        run: |
          python -m venv venvRG
          
          source venvRG/bin/activate 

          ./venvRG/bin/python3 /home/runner/work/TestingRunners/app/randomgrid.py
          
          deactivate

          echo "--- Cleaning up venvRG folder ---"
          rm -rf venvRG
          
          echo "Virtual environment cleanup complete."
